export const keepFlipTheme = {
  fonts: {
    analysis: 'LucidaConsole',
    body: 'SpaceGroteskRegular',
    medium: 'SpaceGroteskMedium',
    semibold: 'SpaceGroteskSemiBold',
    bold: 'SpaceGroteskBold',
    display: 'SpaceGroteskBold',
  },
  colors: {
    background: '#030305',
    backgroundDeep: '#010102',
    backgroundRaised: 'rgba(11, 10, 14, 0.92)',
    surface: '#08080B',
    surfaceSoft: '#15121A',
    gold: '#D7A84A',
    goldBright: '#F2D38A',
    goldMuted: '#8A642B',
    cream: '#faefcfff',
    text: '#F7F2E8',
    textMuted: '#ADA7B2',
    scannerAmber: '#E0AC4B',
    scannerCyan: '#58DFE8',
    scannerViolet: '#8D72FF',
    scannerIndigo: '#FDFBF7',
    scannerWhite: '#FFF2D2',
    danger: '#E86158',
  },
  radii: {
    small: 12,
    medium: 20,
    large: 30,
    pill: 999,
  },
} as const;
