plugins {
  id 'com.android.library'
  id 'expo-module-gradle-plugin'
}

group = 'expo.modules.keepflipinappreview'
version = '0.1.0'

android {
  namespace "expo.modules.keepflipinappreview"
  defaultConfig {
    versionCode 1
    versionName "0.1.0"
  }
  lintOptions {
    abortOnError false
  }
  
  dependencies {
    // Official Google Play In-App Review libraries
    implementation 'com.google.android.play:review:2.0.2'
    implementation 'com.google.android.play:review-ktx:2.0.2'
    }
    
}
